### PR TITLE
created icons with logo

### PR DESCRIPTION
**Pull request by dhitchcock**
I copied Spotify icons and just put in the YTM logo.  hope it's up to snuff!

### CODE REVIEW

**Comment by jiri-janousek** [comment]
Hello @dhitchcock, thanks for your PR. I'm afraid `src/icon-xs.svg` need more tweaking. I'd remove the white circle and expand the play triangle. 

 16×16
 22×22
 24×24

**Review by jiri-janousek — CHANGES_REQUESTED** [review]
src/icon-xs.svg needs fixing.

**Comment by dhitchcock** [comment]
Ahh yeah I see what you mean.  I took another stab at it, tweaked the sm a little too.

**Comment by jiri-janousek** [comment]
Looks good.

**Review by jiri-janousek — APPROVED** [review]

**Comment by jiri-janousek** [comment]
Merged, thanks :+1:

**Pull request merged**
